### ISSUE TITLE
Explore if we can bring in a group from bioeco geonode

### ISSUE THREAD

**Issue by MathewBiddle** [marinebon/map-of-activities#1]
I created a group (map?) of layers for US MBON https://geonode.goosocean.org/maps/1043/embed

I wonder if we can harvest that group?

I'll play around with this.

**Comment by MathewBiddle** [comment]
See https://geonode.goosocean.org/maps/1043

**Comment by MathewBiddle** [comment]
might be able to use owslib https://github.com/python-visualization/folium/blob/main/examples/WmsTimeDimension.ipynb

with the WMS endpoint https://geonode.goosocean.org/capabilities/map/1043/?access_token=YBuSYnyqhY1ZpggDSeU2YcyuhktrgN

**Comment by bbest** [comment]
> I created a group (map?) of layers for US MBON https://geonode.goosocean.org/maps/1043/embed
> 
> I wonder if we can harvest that group?
> 
> I'll play around with this.

Ooh, this looks promising!

<img width="1227" alt="image" src="https://user-images.githubusercontent.com/2837257/225923830-0a136b6a-4b5e-4c59-9c9a-c933b036a036.png">

**Comment by ocefpaf** [comment]
@MathewBiddle it turns out we can request the data on each layer in the map with the API:

https://nbviewer.org/urls/gist.githubusercontent.com/ocefpaf/aa58988e144db886564f04b3325c5f82/raw/7c9072c077367dad8171010446ebb7d53166b48e/fetching_MBON_from_map_1043.ipynb

**Comment by 7yl4r** [comment]
So now we just need a list of layer names

**Comment by MathewBiddle** [comment]
The list of layer names comes from that collection map linked above. So, in the end all you need is that collection map identifier. 

I've been tinkering around with some stuff at https://github.com/MathewBiddle/map-of-activities/tree/add_python

Nearly there...

**Comment by 7yl4r** [comment]
This is looking great, but folium is bogging down in my browser already from those OBIS points. 

We can draw bounding boxes only; maybe there is a way to get a bounding box for the OBIS points.

**Comment by MathewBiddle** [comment]
We tried the bounding boxes, but a lot of them overlap making it difficult to tease out what the popups were linking to. @ocefpaf showed a way to make the points load faster (replacing pins with small circles). See if this helps https://mathewbiddle.github.io/map-of-activities/

I don't seem to have browser bog down issues now...

PR coming soon.
