### ISSUE TITLE
add attr to TileLayer

### ISSUE THREAD

**Issue by MathewBiddle** [marinebon/map-of-activities#11]
The action is failing https://github.com/marinebon/map-of-activities/actions/runs/7056264936/job/19207954892

Need to add `attr=attr,` to:

```
folium.raster_layers.TileLayer(
    'cartodbdark_matter',
     name="CartoDB",
).add_to(m)

folium.raster_layers.TileLayer(
    name="Toner",
    tiles="Stamen Toner",
).add_to(m)
```

**Comment by MathewBiddle** [comment]
@ocefpaf it looks like something changed w/ folium [v0.15](https://github.com/python-visualization/folium/releases/tag/v0.15.0) that now requires `attr` for TileLayer. Or maybe Stammen Toner is deprecated?

**Comment by ocefpaf** [comment]
> @ocefpaf it looks like something changed w/ folium [v0.15](https://github.com/python-visualization/folium/releases/tag/v0.15.0) that now requires `attr` for TileLayer. Or maybe Stammen Toner is deprecated?

Stammen Toner is no longer free. We removed it in 0.15.1 and user can also use xyzservices as the title providers. See https://xyzservices.readthedocs.io/en/stable/ for the list of all the available tiles.

PS: one can still use Stammen Toner if you have an API key.
