### ISSUE TITLE
Action fails to run notebook

### ISSUE THREAD

**Issue by MathewBiddle** [marinebon/map-of-activities#13]
https://github.com/marinebon/map-of-activities/actions/runs/7736796590/job/21094706544

Problem with:
```
jupyter nbconvert --to notebook --execute map-of-activities.ipynb --output=map-of-activities-output.ipynb
```

Error messages:
```
[NbConvertApp] ERROR | Kernel died while waiting for execute reply.
nbclient.exceptions.DeadKernelError: Kernel died
```

**Comment by MathewBiddle** [comment]
seems to run fine locally. Trying to rerun in actions now.

**Comment by MathewBiddle** [comment]
Still failing. https://github.com/marinebon/map-of-activities/actions/runs/7743934360

@ocefpaf any ideas?

We could reorganize this repo by moving the notebook code to a python script and running that. Would eliminate the need for `jupyter nbconvert`, which is what seems to be causing the problem. Would probably install and run faster too?

**Comment by ocefpaf** [comment]
> which is what seems to be causing the problem.

Not sure...

> Would probably install and run faster too?

That is true. You don't need/store the outputs of the notebook, right? I can try that in a PR right now. Hold on...

**Comment by MathewBiddle** [comment]
> You don't need/store the outputs of the notebook, right?

We do. We write out `index.html` to https://github.com/marinebon/map-of-activities/tree/main/docs

Outputs inside the notebook? No.

**Comment by ocefpaf** [comment]
We can keep that with the script if we don't care about opening the notebook. Working on it.
