### ISSUE TITLE
add link(s) to external visualizations of MBON data?

### ISSUE THREAD

**Issue by 7yl4r** [marinebon/map-of-activities#4]
Should we include links to other summaries of MBON datasets? 
This map should be the all-encompassing map and could link out to other views like the occurrence data only.

Example links that could be added:
* for MBON occurrence data in OBIS: https://obis.org/institute/23070
* others?

**Comment by MathewBiddle** [comment]
Maybe update the readme to include the information from the first cell of https://github.com/marinebon/map-of-activities/blob/main/map-of-activities.ipynb?

The way the map is created, it's tricky to add in links on the webpage. Right now I'm using `attr` in `cell[6]` to include additional links in the footer.
